### ISSUE TITLE
Alquilar un garaje

### ISSUE THREAD

**Issue by 3ralon** [Aparking/AparKing_Backend#176]
Esta funcionalidad incluye todos los características que involucran:
- [x] Crear un alquiler: alquilar un garaje desde el anuncio
- [x] Obtener un alquiler: ver los detalles del alquiler
- [x] Eliminar un alquiler: cancelar un alquiler de garaje
- [x] Obtener todos mis alquileres: listar todos mis alquileres
- [x] Selección de método de pago

Colaboradores: @3ralon @ivasansan1
